# import library

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

# load and merge data

In [5]:
df1 = pd.read_csv("/Users/khashiazahira/Desktop/dicoding/CAPSTONE/dataset/main_dataset/job_postings.csv")
df2 = pd.read_csv("/Users/khashiazahira/Desktop/dicoding/CAPSTONE/dataset/main_dataset/job_skills.csv")
df3 = pd.read_csv("/Users/khashiazahira/Desktop/dicoding/CAPSTONE/dataset/main_dataset/dataset_jobstreet.csv")
print("\ncolumns df1 :", df1.columns.tolist())
print("\ncolumns df2 :", df2.columns.tolist())
print("\ncolumns df3 :", df3.columns.tolist())

columns df1 : ['job_link', 'last_processed_time', 'last_status', 'got_summary', 'got_ner', 'is_being_worked', 'job_title', 'company', 'job_location', 'first_seen', 'search_city', 'search_country', 'search_position', 'job_level', 'job_type']

columns df2 : ['job_link', 'job_skills']

columns df3 : ['Judul_Pekerjaan', 'Perusahaan', 'Lokasi', 'Jenis_Pekerjaan', 'Gaji', 'Kualifikasi_Keterampilan', 'URL_Target']

In [6]:
df3_clean = df3[['Judul_Pekerjaan', 'Kualifikasi_Keterampilan']].copy()
df3_clean.rename(columns={
    'Judul_Pekerjaan': 'job_title',
    'Kualifikasi_Keterampilan': 'job_skills'
}, inplace=True)

In [7]:
df = pd.merge(df1,df2, on="job_link", how="inner")
df

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_skills
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite,"Machine Learning, Programming, Python, Scala, ..."
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite,"C++, Python, PyTorch, TensorFlow, MXNet, CUDA,..."
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite,"ETL, Data Integration, Data Transformation, Da..."
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite,"Data Lakes, Data Bricks, Azure Data Factory Pi..."
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,2024-01-21 07:11:22.099082+00,Finished NER,t,t,f,"Data Reporting Manager, FOOTBALL ASSOCIATION",Guardian Jobs,"Wembley, England, United Kingdom",2024-01-16,High Wycombe,United Kingdom,Manager Forms Analysis,Mid senior,Onsite,"Dashboard development, Reporting, Power BI, SQ..."
12213,https://www.linkedin.com/jobs/view/corporate-a...,2024-01-19 15:10:41.177008+00,Finished NER,t,t,f,Corporate AML Alert Investigation Specialist,"Glacier Bancorp, Inc.","Kalispell, MT",2024-01-14,Montana,United States,Teller,Mid senior,Onsite,"Investigation, Antimoney laundering, Fraud, Ba..."
12214,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:20:19.036168+00,Finished NER,t,t,f,Senior Data Scientist,Highnote,"San Francisco, CA",2024-01-16,San Rafael,United States,Mathematician,Mid senior,Onsite,"Data Science, Quantitative Modeling, SQL, Data..."
12215,https://www.linkedin.com/jobs/view/senior-data...,2024-01-19 23:25:28.107523+00,Finished NER,t,t,f,Senior Data Engineer,CompSource Mutual Insurance Company,"Oklahoma City, OK",2024-01-16,Arcadia,United States,Protection Engineer,Mid senior,Onsite,"Data Engineering, Data Quality, SQL, Python, T..."
12216,https://www.linkedin.com/jobs/view/medical-tec...,2024-01-19 23:26:27.593516+00,Finished NER,t,t,f,"Medical Technologist, MLS or MLT",Community Health Systems,"Mooresville, NC",2024-01-14,Salisbury,United States,Biologist,Mid senior,Onsite,"Medical Technology, MLS, Microbiology, Clinica..."

In [8]:
fix_df= df[["job_title", "job_skills"]].copy()
fix_df

,job_title,job_skills
0,Senior Machine Learning Engineer,"Machine Learning, Programming, Python, Scala, ..."
1,"Principal Software Engineer, ML Accelerators","C++, Python, PyTorch, TensorFlow, MXNet, CUDA,..."
2,Senior ETL Data Warehouse Specialist,"ETL, Data Integration, Data Transformation, Da..."
3,Senior Data Warehouse Developer / Architect,"Data Lakes, Data Bricks, Azure Data Factory Pi..."
4,Lead Data Engineer,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S..."
...,...,...
12212,"Data Reporting Manager, FOOTBALL ASSOCIATION","Dashboard development, Reporting, Power BI, SQ..."
12213,Corporate AML Alert Investigation Specialist,"Investigation, Antimoney laundering, Fraud, Ba..."
12214,Senior Data Scientist,"Data Science, Quantitative Modeling, SQL, Data..."
12215,Senior Data Engineer,"Data Engineering, Data Quality, SQL, Python, T..."
12216,"Medical Technologist, MLS or MLT","Medical Technology, MLS, Microbiology, Clinica..."

combined df1&df2 dengan df3

In [9]:
df_combined =pd.concat([fix_df, df3_clean], ignore_index=True)

In [10]:
df_combined

,job_title,job_skills
0,Senior Machine Learning Engineer,"Machine Learning, Programming, Python, Scala, ..."
1,"Principal Software Engineer, ML Accelerators","C++, Python, PyTorch, TensorFlow, MXNet, CUDA,..."
2,Senior ETL Data Warehouse Specialist,"ETL, Data Integration, Data Transformation, Da..."
3,Senior Data Warehouse Developer / Architect,"Data Lakes, Data Bricks, Azure Data Factory Pi..."
4,Lead Data Engineer,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S..."
...,...,...
14700,Project Manager,NaN
14701,Head of Development Team,Merancang dan mengimplementasikan programPelat...
14702,Lowongan Kerja Eos Engineer On Site Lintas Med...,Memiliki kemampuan troubleshooting perangkat e...
14703,Software Developer,Melakukan pengembangan terhadap program-progra...
14704,Lowongan Kerja Full Stack Web Developer Nexgen...,Develop and maintain web applications (both fr...

# data cleaning (handling missing and duplicate values)

In [11]:
print(f"missing values:\n", df_combined.isnull().sum())

print(f"\ntotal duplicated data:\n", df_combined.duplicated().sum())

missing values:
 job_title       0
job_skills    466
dtype: int64

total duplicated data:
 80

In [12]:
df_combined= df_combined.dropna().drop_duplicates()

In [13]:
print("After data cleaning ")
print(f"\nMissing values:\n", df_combined.isnull().sum())

print(f"\nTotal duplicated data:\n", df_combined.duplicated().sum())

After data cleaning

Missing values:
 job_title     0
job_skills    0
dtype: int64

Total duplicated data:
 0

feature extraction column (cleaned_skills)

In [14]:
import re

# Buat Kamus Induk berisi daftar skill IT
master_skills_list = [
    'python', 'java', 'c#', 'c/c++', 'c++', 'c', 'javascript', 'typescript',
    'go', 'golang', 'php', 'ruby', 'swift', 'objective-c', 'kotlin', 'dart',
    'bash', 'shell script', 'powershell', 'sql', 'pl/sql', 'dax', 'html', 'html5', 'css', 'css3', 'sass', 'less',

    'react', 'react.js', 'reactjs', 'next.js', 'angular', 'vue', 'vue.js', 'vuejs', 'nuxt',
    'node.js', 'nodejs', 'express', 'nest.js', 'jquery', 'ajax', 'bootstrap', 'tailwind css',
    'spring boot', 'spring mvc', 'spring cloud', 'laravel', 'codeigniter', 'yii2', 'django', 'flask', 'fastapi',
    'flutter', 'react native', 'ionic',

    'mysql', 'postgresql', 'postgre', 'sql server', 'ms sql', 'oracle', 'db2',
    'mongodb', 'redis', 'elasticsearch', 'cassandra', 'mariadb', 'hadoop', 'spark', 'hive', 'impala',
    'chromadb', 'pinecone', 'weaviate', 'milvus', 'pgvector',

    'aws', 'azure', 'gcp', 'google cloud', 'alicloud', 'digitalocean',
    'docker', 'kubernetes', 'k8s', 'openshift', 'docker swarm', 'proxmox', 'vmware', 'hyper-v',
    'ci/cd', 'jenkins', 'gitlab ci', 'github actions', 'circle ci', 'bamboo', 'argo cd',
    'terraform', 'ansible', 'linux', 'ubuntu', 'centos', 'debian', 'rhel', 'windows server',
    'nginx', 'apache', 'iis',

    'mikrotik', 'cisco', 'huawei', 'juniper', 'fortinet', 'palo alto', 'aruba', 'ubiquiti',
    'tcp/ip', 'dns', 'dhcp', 'vlan', 'vpn', 'bgp', 'ospf', 'mpls', 'sd-wan', 'ftth', 'fiber optic',
    'firewall', 'ids/ips', 'siem', 'soar', 'splunk', 'qradar', 'datadog', 'grafana', 'prometheus', 'zabbix', 'prtg',
    'penetration testing', 'vapt', 'ceh', 'cissp', 'cism', 'comptia security+', 'owasp', 'wireshark',
    'active directory', 'ldap', 'sso', 'oauth', 'jwt',

    'sap', 'sap s/4hana', 'sap ecc', 'sap fico', 'sap mm', 'sap sd', 'sap pp', 'sap qm', 'sap pm', 'sap wm', 'sap ewm',
    'sap abap', 'sap successfactors', 'sap b1', 'sap business one',
    'odoo', 'microsoft dynamics 365', 'salesforce', 'sharepoint', 'idempiere',
    'oracle ebs', 'microsoft 365', 'google workspace',

    'excel', 'power bi', 'tableau', 'looker', 'metabase', 'qlik', 'google analytics',
    'apache airflow', 'talend', 'ssis', 'ssas', 'ssrs', 'etl', 'elt', 'data warehouse', 'data modeling',

    'machine learning', 'artificial intelligence', 'ai', 'nlp', 'computer vision', 'deep learning',
    'llm', 'rag', 'prompt engineering', 'pytorch', 'tensorflow', 'scikit-learn', 'langchain', 'llama', 'openai',
    'uipath', 'zapier', 'make.com', 'n8n', 'power automate', 'power apps', 'rpa',

    'katalon', 'selenium', 'jmeter', 'cypress', 'playwright', 'appium', 'postman', 'swagger',
    'sqa', 'manual testing', 'automation testing', 'uat', 'tdd', 'bdd', 'loadrunner',

    'figma', 'adobe xd', 'sketch', 'autocad', 'illustrator', 'photoshop',
    'jira', 'trello', 'confluence', 'notion', 'agile', 'scrum', 'kanban', 'waterfall',
    'pmp', 'prince2', 'itil', 'cobit', 'iso 27001', 'sdlc',

    'cctv', 'troubleshooting hardware', 'plc', 'scada', 'iot', 'mes', 'opc-ua', 'modbus',
    'git', 'github', 'gitlab', 'bitbucket', 'svn', 'version control', 'rest api', 'graphql', 'grpc', 'soap',
    'rabbitmq', 'kafka', 'microservices', 'clean architecture'
]

import pandas as pd

# Urutkan berdasarkan panjang karakter
master_skills_list.sort(key=len, reverse=True)

def extract_clean_skills(text):
    if pd.isna(text):
        return ""

    text = text.lower()
    extracted_skills = set()

    for skill in master_skills_list:
        # Pengecualian khusus untuk karakter yang sulit di-regex batasannya
        if skill in ['c/c++', 'c++', 'c#', 'node.js', 'vue.js', 'react.js', 'next.js']:
            if skill in text:
                extracted_skills.add(skill)
                text = text.replace(skill, "")
        else:
            # Menggunakan regex word boundary
            pattern = r'\b' + re.escape(skill) + r'\b'
            if re.search(pattern, text):
                extracted_skills.add(skill)
                text = re.sub(pattern, "", text)

    return ", ".join(sorted(list(extracted_skills)))

df_combined['cleaned_skills'] = df_combined['job_skills'].apply(extract_clean_skills)

# Tampilkan perbandingan sebelum dan sesudah
print(df_combined[['job_skills', 'cleaned_skills']].head())

                                          job_skills  \
0  Machine Learning, Programming, Python, Scala, ...
1  C++, Python, PyTorch, TensorFlow, MXNet, CUDA,...
2  ETL, Data Integration, Data Transformation, Da...
3  Data Lakes, Data Bricks, Azure Data Factory Pi...
4  Java, Scala, Python, RDBMS, NoSQL, Redshift, S...

                                      cleaned_skills
0  ai, java, machine learning, python, pytorch, s...
1  c++, computer vision, deep learning, linux, py...
2  apache, aws, azure, data modeling, data wareho...
3  azure, data warehouse, elt, etl, python, spark...
4  agile, aws, azure, cassandra, google cloud, ha...

In [15]:
df_combined

,job_title,job_skills,cleaned_skills
0,Senior Machine Learning Engineer,"Machine Learning, Programming, Python, Scala, ...","ai, java, machine learning, python, pytorch, s..."
1,"Principal Software Engineer, ML Accelerators","C++, Python, PyTorch, TensorFlow, MXNet, CUDA,...","c++, computer vision, deep learning, linux, py..."
2,Senior ETL Data Warehouse Specialist,"ETL, Data Integration, Data Transformation, Da...","apache, aws, azure, data modeling, data wareho..."
3,Senior Data Warehouse Developer / Architect,"Data Lakes, Data Bricks, Azure Data Factory Pi...","azure, data warehouse, elt, etl, python, spark..."
4,Lead Data Engineer,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S...","agile, aws, azure, cassandra, google cloud, ha..."
...,...,...,...
14699,IT MULTIMEDIA / DESAIN GRAFIS,Membuat desain konten untuk kebutuhan marketin...,"illustrator, photoshop"
14701,Head of Development Team,Merancang dan mengimplementasikan programPelat...,
14702,Lowongan Kerja Eos Engineer On Site Lintas Med...,Memiliki kemampuan troubleshooting perangkat e...,cctv
14703,Software Developer,Melakukan pengembangan terhadap program-progra...,"docker, git, javascript, laravel, node.js, php..."
14704,Lowongan Kerja Full Stack Web Developer Nexgen...,Develop and maintain web applications (both fr...,"ai, angular, aws, css, git, html, java, javasc..."

In [16]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14213 entries, 0 to 14704
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       14213 non-null  object
 1   job_skills      14213 non-null  object
 2   cleaned_skills  14213 non-null  object
dtypes: object(3)
memory usage: 444.2+ KB

# memfilter Job IT

In [17]:
import pandas as pd
import re

# Kata Kunci Spesifik
bounded_keywords = [
    'ai', 'qa', 'ui', 'ux', 'it', 'noc', 'soc', 'dba', 'sap', 'edp'
]

# Kata Kunci Substring Umum
substring_keywords = [
    'developer', 'engineer', 'programmer', 'software', 'frontend', 'backend', 'fullstack',
    'data scientist', 'data analyst', 'data engineer', 'machine learning', 'artificial intelligence',
    'cloud', 'devops', 'sre', 'security', 'cyber', 'penetration',
    'database', 'product manager', 'product owner', 'tester', 'sdet',
    'embedded', 'iot', 'game', 'web', 'network', 'system administrator', 'sysadmin',
    'infrastructure', 'architect', 'technical lead', 'tech lead', 'scrum master', 'agile',
    'information technology', 'helpdesk', 'system', 'business analyst',
    'data warehouse', 'erp', 'odoo', 'salesforce', 'machine vision', 'deep learning',
    'data center', 'teknisi', 'administrator', 'automation', 'digital', 'teknologi',
    'komputer', 'informatika', 'hardware', 'desktop', 'server', 'apps', 'ict', 'aplikasi',
    'python', 'java', 'c#', 'c/c++', 'c++', 'c', 'javascript', 'typescript',
    'go', 'golang', 'php', 'ruby', 'swift', 'objective-c', 'kotlin', 'dart',
    'bash', 'shell script', 'powershell', 'sql', 'pl/sql', 'dax', 'html', 'html5', 'css', 'css3', 'sass', 'less',

    'react', 'react.js', 'reactjs', 'next.js', 'angular', 'vue', 'vue.js', 'vuejs', 'nuxt',
    'node.js', 'nodejs', 'express', 'nest.js', 'jquery', 'ajax', 'bootstrap', 'tailwind css',
    'spring boot', 'spring mvc', 'spring cloud', 'laravel', 'codeigniter', 'yii2', 'django', 'flask', 'fastapi',
    'flutter', 'react native', 'ionic',

    'mysql', 'postgresql', 'postgre', 'sql server', 'ms sql', 'oracle', 'db2',
    'mongodb', 'redis', 'elasticsearch', 'cassandra', 'mariadb', 'hadoop', 'spark', 'hive', 'impala',
    'chromadb', 'pinecone', 'weaviate', 'milvus', 'pgvector',

    'aws', 'azure', 'gcp', 'google cloud', 'alicloud', 'digitalocean',
    'docker', 'kubernetes', 'k8s', 'openshift', 'docker swarm', 'proxmox', 'vmware', 'hyper-v',
    'ci/cd', 'jenkins', 'gitlab ci', 'github actions', 'circle ci', 'bamboo', 'argo cd',
    'terraform', 'ansible', 'linux', 'ubuntu', 'centos', 'debian', 'rhel', 'windows server',
    'nginx', 'apache', 'iis',

    'mikrotik', 'cisco', 'huawei', 'juniper', 'fortinet', 'palo alto', 'aruba', 'ubiquiti',
    'tcp/ip', 'dns', 'dhcp', 'vlan', 'vpn', 'bgp', 'ospf', 'mpls', 'sd-wan', 'ftth', 'fiber optic',
    'firewall', 'ids/ips', 'siem', 'soar', 'splunk', 'qradar', 'datadog', 'grafana', 'prometheus', 'zabbix', 'prtg',
    'penetration testing', 'vapt', 'ceh', 'cissp', 'cism', 'comptia security+', 'owasp', 'wireshark',
    'active directory', 'ldap', 'sso', 'oauth', 'jwt',

    'sap', 'sap s/4hana', 'sap ecc', 'sap fico', 'sap mm', 'sap sd', 'sap pp', 'sap qm', 'sap pm', 'sap wm', 'sap ewm',
    'sap abap', 'sap successfactors', 'sap b1', 'sap business one',
    'odoo', 'microsoft dynamics 365', 'salesforce', 'sharepoint', 'idempiere',
    'oracle ebs', 'microsoft 365', 'google workspace',

    'excel', 'power bi', 'tableau', 'looker', 'metabase', 'qlik', 'google analytics',
    'apache airflow', 'talend', 'ssis', 'ssas', 'ssrs', 'etl', 'elt', 'data warehouse', 'data modeling',

    'machine learning', 'artificial intelligence', 'ai', 'nlp', 'computer vision', 'deep learning',
    'llm', 'rag', 'prompt engineering', 'pytorch', 'tensorflow', 'scikit-learn', 'langchain', 'llama', 'openai',
    'uipath', 'zapier', 'make.com', 'n8n', 'power automate', 'power apps', 'rpa',

    'katalon', 'selenium', 'jmeter', 'cypress', 'playwright', 'appium', 'postman', 'swagger',
    'sqa', 'manual testing', 'automation testing', 'uat', 'tdd', 'bdd', 'loadrunner',

    'figma', 'adobe xd', 'sketch', 'autocad', 'illustrator', 'photoshop',
    'jira', 'trello', 'confluence', 'notion', 'agile', 'scrum', 'kanban', 'waterfall',
    'pmp', 'prince2', 'itil', 'cobit', 'iso 27001', 'sdlc',

    'cctv', 'troubleshooting hardware', 'plc', 'scada', 'iot', 'mes', 'opc-ua', 'modbus',
    'git', 'github', 'gitlab', 'bitbucket', 'svn', 'version control', 'rest api', 'graphql', 'grpc', 'soap',
    'rabbitmq', 'kafka', 'microservices', 'clean architecture'
]

# Merakit Pola Pencarian Regex
# mengabaikan huruf besar/kecil
pattern = (
    r'(?i)('
    + '|'.join([rf'\b{re.escape(kw)}\b' for kw in bounded_keywords])
    + '|'
    + '|'.join([re.escape(kw) for kw in substring_keywords])
    + ')'
)
# Menerapkan Filter ke Dataframe
df_it_only = df_combined[df_combined['job_title'].str.contains(pattern, na=False)].copy()

print(f"Total baris sebelum filter: {len(df_combined)}")
print(f"Total baris setelah filter IT: {len(df_it_only)}")

/var/folders/fh/3rw7ypm52s79sv5l1sp19zg00000gn/T/ipykernel_35687/1442318133.py:80: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_it_only = df_combined[df_combined['job_title'].str.contains(pattern, na=False)].copy()

Total baris sebelum filter: 14213
Total baris setelah filter IT: 13544

In [18]:
# Menghapus baris di mana 'cleaned_skills' berupa string kosong
df_final = df_it_only[df_it_only['cleaned_skills'] != ""].copy()

df_final.dropna(subset=['cleaned_skills'], inplace=True)

# Reset index agar urutan baris kembali rapi
df_final.reset_index(drop=True, inplace=True)

# Tampilkan perbandingan jumlah baris
print(f"Jumlah data sebelum dihapus skill kosong: {len(df_it_only)}")
print(f"Jumlah data SETELAH dihapus skill kosong: {len(df_final)}")

# Ekspor hasil
df_final.to_csv('final_ready_it_jobs.csv', index=False)
print("Data final berhasil disimpan ke 'final_ready_it_jobs.csv'!")

Jumlah data sebelum dihapus skill kosong: 13544
Jumlah data SETELAH dihapus skill kosong: 11065
Data final berhasil disimpan ke 'final_ready_it_jobs.csv'!

In [19]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11065 entries, 0 to 11064
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       11065 non-null  object
 1   job_skills      11065 non-null  object
 2   cleaned_skills  11065 non-null  object
dtypes: object(3)
memory usage: 259.5+ KB

In [20]:
def assign_job_category(title):
    """
    Memetakan job_title ke 7 kategori profesi utama.
    Profesi di luar 7 target utama akan dipetakan ke 'Other IT'.
    """
    if pd.isna(title):
        return 'Other IT'
    t = title.lower()

    # 1. Antisipasi False Positives (Cek ini di awal)
    if 'data loss prevention' in t or 'dlp' in t:
        return 'Other IT' # Atau 'Security' jika ingin tetap dianalisis

    # 2. AI / Machine Learning Engineer
    if any(k in t for k in [
        'machine learning', 'ml engineer', 'ai engineer', 'artificial intelligence',
        'deep learning', 'nlp', 'computer vision', 'mlops'
    ]):
        return 'AI / Machine Learning Engineer'

    # 3. Data Scientist
    if any(k in t for k in ['data scientist', 'data science', 'research scientist']):
        return 'Data Scientist'

    # 4. Data Engineer
    if any(k in t for k in [
        'data engineer', 'data architect', 'database administrator', 'dba',
        'analytics engineer', 'big data'
    ]):
        return 'Data Engineer'

    # 5. Data Analyst
    if any(k in t for k in [
        'data analyst', 'bi developer', 'business intelligence', 'data visualization'
    ]):
        return 'Data Analyst'

    # 6. Fullstack Developer
    if any(k in t for k in ['full stack', 'fullstack', 'full-stack']):
        return 'Fullstack Developer'

    # 7. Frontend Developer
    if any(k in t for k in [
        'frontend', 'front-end', 'front end', 'ui developer', 'react developer',
        'vue developer', 'angular developer'
    ]):
        return 'Frontend Developer'

    # 8. Backend Developer
    if any(k in t for k in [
        'backend', 'back-end', 'back end', 'software engineer', 'software developer',
        'python developer', 'java developer', 'php developer', 'node developer',
        'golang', 'api developer'
    ]):
        return 'Backend Developer'

    # Jika tidak masuk 7 role di atas, buang ke Other IT
    return 'Other IT'


df_final['job_category'] = df_final['job_title'].apply(assign_job_category)

print('Distribusi job_category:')
print(df_final['job_category'].value_counts())
print(f'\nTotal baris: {len(df_final)}')

Distribusi job_category:
job_category
Other IT                          4307
Data Engineer                     2486
Data Analyst                      1807
AI / Machine Learning Engineer    1032
Data Scientist                     948
Backend Developer                  311
Fullstack Developer                138
Frontend Developer                  36
Name: count, dtype: int64

Total baris: 11065

In [21]:
# Memfilter dataframe untuk membuang 'Other IT'
df_final_filtered = df_final[df_final['job_category'] != 'Other IT'].copy()

# Mengecek distribusi data setelah difilter
print("=== Distribusi 7 Role Capstone ===")
print(df_final_filtered['job_category'].value_counts())

# Mengecek total baris yang tersisa
print(f'\nTotal baris awal: {len(df_final)}')
print(f'Total baris sekarang (setelah Other IT di-drop): {len(df_final_filtered)}')

=== Distribusi 7 Role Capstone ===
job_category
Data Engineer                     2486
Data Analyst                      1807
AI / Machine Learning Engineer    1032
Data Scientist                     948
Backend Developer                  311
Fullstack Developer                138
Frontend Developer                  36
Name: count, dtype: int64

Total baris awal: 11065
Total baris sekarang (setelah Other IT di-drop): 6758

In [22]:
df_final_filtered.to_csv('7role.csv', index=False)

In [23]:
df_final_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6758 entries, 0 to 11064
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_title       6758 non-null   object
 1   job_skills      6758 non-null   object
 2   cleaned_skills  6758 non-null   object
 3   job_category    6758 non-null   object
dtypes: object(4)
memory usage: 264.0+ KB